### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `loading`.  If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}. 

### ISSUE THREAD

**Issue by vikashkumar-19** [hunghg255/reactjs-tiptap-editor#122]
Received this error message on every client first call on console, 

on debug it is causing issue due to `loading` prop in `ActionButton` Component. It passes this boolean value to a Dom element.

The issue arises because the loading prop is included in the rest object (...rest), which is forwarded to the Comp (either Slot or Toggle). If Toggle or any downstream component renders a native DOM element like a <button>, the loading prop will get passed directly to it, causing the warning.

### Btw, I really liked this library and would love to contribute in it. Let me know if i can pull request with below PATCH

```
Index: src/components/ActionButton.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/components/ActionButton.tsx b/src/components/ActionButton.tsx
--- a/src/components/ActionButton.tsx	(revision beee54297f2723fd2713e9e298073b2643955aa0)
+++ b/src/components/ActionButton.tsx	(date 1734516172227)
@@ -50,7 +50,7 @@
       disabled = false,
       customClass = '',
       // color = undefined,
-      // loading = false,
+      loading = undefined,
       shortcutKeys = undefined,
       tooltipOptions = {},
       action = undefined,
@@ -75,7 +75,7 @@
             disabled={disabled}
             onClick={action}
             data-state={isActive?.() ? 'on' : 'off'}
-            {...rest}
+            {...(rest as Omit<typeof rest, 'loading'>)}
           >
             {Icon && <Icon className="richtext-w-4 richtext-h-4" />}
             {children}
```

### Error Message

```
Warning: Received `false` for a non-boolean attribute `loading`.

If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}.

If you used to conditionally omit it with loading={condition && value}, pass loading={condition ? value : undefined} instead.
    at button
    at http://localhost:8000/node_modules/.vite/deps/chunk-CQY5K356.js?v=e333c348:41:13
    at http://localhost:8000/node_modules/.vite/deps/@radix-ui_react-toggle.js?v=e333c348:26:20
    at http://localhost:8000/@fs/Users/ravsteel/work/projects/experiments/reactjs-tiptap-editor/lib/utils-kFjUOXAt.js:470:16
    at http://localhost:8000/node_modules/.vite/deps/chunk-7PUNJEA3.js?v=e333c348:52:11
    at http://localhost:8000/node_modules/.vite/deps/chunk-7PUNJEA3.js?v=e333c348:33:11
    at http://localhost:8000/node_modules/.vite/deps/chunk-CQY5K356.js?v=e333c348:41:13
    at http://localhost:8000/node_modules/.vite/deps/chunk-7PUNJEA3.js?v=e333c348:52:11
    at http://localhost:8000/node_modules/.vite/deps/chunk-7PUNJEA3.js?v=e333c348:33:11
    at http://localhost:8000/node_modules/.vite/deps/chunk-CQY5K356.js?v=e333c348:41:13
    at http://localhost:8000/node_modules/.vite/deps/chunk-XP5UWHXG.js?v=e333c348:1872:13
    at http://localhost:8000/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=e333c348:197:13
    at Provider (http://localhost:8000/node_modules/.vite/deps/chunk-6AP5US4G.js?v=e333c348:38:15)
    at Provider (http://localhost:8000/node_modules/.vite/deps/chunk-2HWUI44S.js?v=e333c348:21:15)
    at Popper (http://localhost:8000/node_modules/.vite/deps/chunk-XP5UWHXG.js?v=e333c348:1864:11)
    at Tooltip (http://localhost:8000/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=e333c348:106:5)
    at http://localhost:8000/@fs/Users/ravsteel/work/projects/experiments/reactjs-tiptap-editor/lib/utils-kFjUOXAt.js:62:15
    at div
    at Jd (http://localhost:8000/@fs/Users/ravsteel/work/projects/experiments/reactjs-tiptap-editor/lib/utils-kFjUOXAt.js:11529:18)
    at div
    at div
    at div
    at as (http://localhost:8000/@fs/Users/ravsteel/work/projects/experiments/reactjs-tiptap-editor/lib/utils-kFjUOXAt.js:2839:11)
    at div
    at div
    at Provider (http://localhost:8000/node_modules/.vite/deps/chunk-6AP5US4G.js?v=e333c348:38:15)
    at TooltipProvider (http://localhost:8000/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=e333c348:62:5)
    at div
    at rs (http://localhost:8000/@fs/Users/ravsteel/work/projects/experiments/reactjs-tiptap-editor/lib/utils-kFjUOXAt.js:2764:16)
    at div
    at App (http://localhost:8000/src/App.tsx:199:33)
```

**Comment by hunghg255** [comment]
@vikashkumar-19 yeah, thank you. PR welcome,

**Comment by vikashkumar-19** [comment]
@hunghg255 PR -> https://github.com/hunghg255/reactjs-tiptap-editor/pull/123
